apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-dev-tools
spec:
  selector:
    matchLabels:
      app: node-dev-tools
  replicas: 1
  template:
    metadata:
      labels:
        app: node-dev-tools
    spec:
      containers:
      - name: node-dev-tools
        image: registry2.wallid.io/base/nodejs-dev-tools:v6
        env:
        - name: PORT
          value: '3000'
        ports:
        - containerPort: 3000
      imagePullSecrets:
          - name: regcred
